function [yhh,yfs2,yf2,aa,bb,HH,WW,NFFT,f]=Notch(Fssss,yh,Wp1p,Wp2p,Ws1s,Ws2s,Rpp2,Rss2);
% % Wpp2=[58 65];      %%%%%Frecuencia de corte del filtro RB%%%%%%%%%%%%%%%%%%
% % Wss2=[60 61];      %%%%%Frecuencia de atenuación del filtro RB%%%%%%%%%%%%%
% % Rpp2=3;            %%%%%Atenuación para la banda rechazada en dB RB%%%%%%%%
% % Rss2=40;           %%%%%Atenuación para la banda rechazada en dB RB%%%%%%%%
fe=Fssss/2;           %%%%%Frecuencia de Nyquist%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Resultat=[Wp1p Wp2p];
Wpp2=Resultat;
Resultat=[Ws1s Ws2s];
Wss2=Resultat;
Wpp=Wpp2/fe;       %%%%%Frecuencia de corte normalizada de filtro%%%%%%%%%%
Wss=Wss2/fe;       %%%%%Frecuencia de atenuación normalizada del filtro%%%%
[nn,Wnn]=buttord(Wpp,Wss,Rpp2,Rss2);
[bb,aa]=butter(nn,Wnn,'stop');
[HH,WW]=freqz(bb,aa,[],Fssss);
yhh=filter(bb,aa,yh);
L=length(yh);
NFFT=2^nextpow2(L);                %%%%Siguiente potencia de 2 del vector y
f=Fssss/2*linspace(0,1,NFFT/2+1);
yf2=fft(yhh,NFFT)/L;
yfs2=fft(yh,NFFT)/L;